AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

require:
  - rubocop-minitest
  - rubocop-rake

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   Enabled: true
#   EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - gitwrab.gemspec
    - test/**/*.rb
